### ISSUE TITLE
[FR] Application properties

### ISSUE THREAD

**Issue by ildar** [dkanada/OpenAPK#12]
The must-have button is Application Properties (Settings Intent).
It allows you(besides other things) Clear app Data/Cache on root-less Androids. Like in [Cache Cleaner](https://f-droid.org/repository/browse/?fdid=com.frozendevs.cache.cleaner)

**Comment by dkanada** [comment]
Mostly finished with this one but I need to make room somewhere in the app activity before I add this. At the moment the icons are getting cut off and I am not a fan of the labels. I also want to add room to expand in the future.

I could move hide and disable to switches instead and add the settings button as an icon but I think that would be too many different layouts on one page. I was also considering removing the labels, do you think they are clear enough as icons? I am planning on adding submenus for permissions and maybe I could move the properties into a submenu as well, so many options.
