### ISSUE TITLE
SD card install

### ISSUE THREAD

**Issue by dimqua** [dkanada/OpenAPK#17]
Please allow to install the app to SD card.

**Comment by dkanada** [comment]
Can you post your phone model, operating system, and path to the SD card? I haven't looked into this much but I do know that SD card access is a pain throughout Android, those specs would help me out.

**Comment by dimqua** [comment]
I mean I can't transfer the app to external storage (SD card). See: https://developer.android.com/guide/topics/data/install-location.html

**Comment by dkanada** [comment]
Should be fixed in the next update, thanks for letting me know.
