### ISSUE TITLE
Feature Request: Remove blue Plus in App Options

### ISSUE THREAD

**Issue by jw243** [dkanada/OpenAPK#3]
I would prefer it, if all app manipulation options appeared in one (scrollable) list instead of finding "disable", " hide" and "share" behind the blue Plus. That way, I would need one click less and would also see immediately the status of the app.

It would also be nice to have more manipulation options in the app lists besides "extract" and "share".

Keep up the good work!

**Comment by dkanada** [comment]
I am hoping to completely redesign the AppActivity page at some point but have not decided on the layout yet. I want to have one section with information about the app and another for available actions. I will probably include a separate section for the app permissions even further down the road. If you have any ideas for the new layout feel free to post them here.

**Comment by dkanada** [comment]
The latest update completely changes the app layout, let me know what you think. This is just a first iteration, I will be making slight changes over time to improve it further. I am closing this issue but if you would like to make another one for the hide and share buttons on the app lists feel free, I would definitely like to add more options for the buttons in the future.

**Comment by jw243** [comment]
I really like the new design of the app pages. Very informative, very clear, superb layout.

One minor bug that I found: it would be nice if the manipulation buttons changed immediately once pressed. E.g. when I press the hide button, it should change immediately to unhide.

It would be great if all six manipulation buttons appeared also in the app overview lists, in addition to extract and share.

By the way, can I help with the german translation?

**Comment by dkanada** [comment]
I will work on those two items soon. Yeah, submit a pull request with the German translation and I can merge it.
