### ISSUE TITLE
Quick action color fixed

### ISSUE THREAD

**Issue by DJaeger** [dkanada/OpenAPK#6]
In the latest version (1.1.1 ) the text and background  color of the quick action buttons seems to be the same for light and dark theme, which is bad to read in light theme.

**Comment by DJaeger** [comment]
![tmp_15496-20170418_102209-2081017021](https://cloud.githubusercontent.com/assets/3408882/25121310/96775df2-2421-11e7-9649-e7941813ac5e.png)

**Comment by dkanada** [comment]
Wow there are a lot of issues with the UI on smaller screens, thanks for letting me know. I will fix the wrapping text along with the incorrect button color. Are there any issues on other pages in the app?

**Comment by dkanada** [comment]
Apparently referencing an issue in a commit automatically closes it, I wanted to make sure there were no other issues with the UI before pushing an update to F-Droid, let me know if you notice any.

**Comment by DJaeger** [comment]
I don't recognize any other UI issues.
Thanks for fixing.

**Comment by DJaeger** [comment]
The (bottom) padding of the buttons at the end seems to be a little bit small.

And a longer data path also breaks the text.


-- 

Mit freundlichen Grüßen

Daniel Jäger

Am 18. April 2017 13:47:09 MESZ schrieb dkanada <notifications@github.com>:

**Comment by DJaeger** [comment]
![3df56d18-2462-11e7-9479-7fb77b6a8ce7](https://cloud.githubusercontent.com/assets/3408882/25141144/ec6cc224-2462-11e7-80da-166a8c26787b.png)

The (bottom) padding of the buttons at the end seems to be a little bit small.

And a longer data path also breaks the text.

Thanks for fixing.

**Comment by dkanada** [comment]
Okay I have fixed those issues too, its kind of a temporary fix because they wont scale perfectly on any screen but it will look better than before. Hopefully I can implement a more permanent fix in the future. The update should be on F-Droid in a few days if you didn't build from the source.

**Comment by DJaeger** [comment]
Thanks

**Comment by DJaeger** [comment]
The bottom buttons now have less bottom padding, not more.
I also would cut off the data path like you have done it now.
The quick action buttons are now fixed.

![tmp_20488-20170424_16234726625721](https://cloud.githubusercontent.com/assets/3408882/25341832/767c3f16-290a-11e7-8d58-54006af36603.png)
